### ISSUE TITLE
Address required field error when used in customer's address book

### ISSUE THREAD

**Issue by justinaht** [calcurates/module-magento#8]
Hi team, i have an issue getting shipping method from calcurate when using address from customer address book
![image](https://github.com/calcurates/module-magento/assets/1575261/35fc0abd-18ee-4a17-bbaa-e91f2ab73155)
![image](https://github.com/calcurates/module-magento/assets/1575261/2f06e22e-e7e7-4ef5-8bee-49af2a1e4ec1)
I have config require state in admin
![image](https://github.com/calcurates/module-magento/assets/1575261/07133ace-24b3-4026-8ea6-fe59d9dbbee0)
Can you check it for me?

**Comment by justinaht** [comment]
Hi @Gemorroj Is there any update for this issue?

**Comment by kolevich** [comment]
Hi @justinaht,
We still don't see that Calcurates causes this issue and couldn't reproduce it locally. It seems it is caused by Magento core issue or similar, which is related to different sets of required fields for customer address and checkout address. Even if the customer address convertation into the shipping address for checkout has some issues, it is not related to the scope of Calcurates extension functionality. Hope this helps. Let us know if you have more questions.

**Comment by justinaht** [comment]
Hi @kolevich , I don't think so. I have checked the entire code and do not see any customization related to the Calcurate module
Pls see this video
https://www.loom.com/share/0c8aaed0bd3e4f07b74eb0b3ecb8f33f
Thanks

**Comment by justinaht** [comment]
Hi @kolevich , I don't think so. I have checked the entire code and do not see any customization related to the Calcurate module
Pls see this video
https://www.loom.com/share/f6cd138583a34d67827ec53c386b72da?sid=73323317-d770-4fc2-a9a0-075eaabea18a
https://www.loom.com/share/0c8aaed0bd3e4f07b74eb0b3ecb8f33f
Thanks

**Comment by kolevich** [comment]
Hi @justinaht,
Your first Loom video has been recorded by me as I was trying to explain the issue to Wade's developers.

1) We failed to reproduce your issue in the default Magento that has no customizations, see my video - https://www.loom.com/share/dc87d16cda4c4015a5005532e962f415

> I have checked the entire code and do not see any customization related to the Calcurate module
2) We can see at least 2 customizations in the "Add Shipping Address" process that can potentially affect the address data that comes from Magento to Calcurates extension:
<img width="626" alt="Screenshot 2023-09-20 at 16 52 00" src="https://github.com/calcurates/module-magento/assets/45657789/89786ec8-a89c-4653-bb00-27c3690a526e">

I suggest testing it without those customizations.

**Comment by justinaht** [comment]
Hi @kolevich 
Do you check the config require state in administrator ?
![image](https://github.com/calcurates/module-magento/assets/1575261/a7aa6829-d4c1-48a3-bf20-38e3f9eb5435)
![image](https://github.com/calcurates/module-magento/assets/1575261/adf2d276-c31c-46c5-8631-1e53518debfe)
According to your video, the state is not required to be filled in. I tried leaving settings require state for UK and it worked.
But adding settings state for UK is not working
Can you check again for me?
Thanks

**Comment by kolevich** [comment]
@justinaht I've changed it to "required" for the UK and nothing changes — I am getting exactly the same correct behaviour when I am passing my test scenario.
https://www.loom.com/share/070f7285505944079a1a99259158ed22?sid=eed9038a-0a90-45c5-9afc-29fd85a73881

**Comment by HardikGS** [comment]
Hi Kolevich,

If you check this video again, https://www.loom.com/share/0c8aaed0bd3e4f07b74eb0b3ecb8f33f
There are 2 things happening here,
1. If a user has selected default address as UK Address and when he goes to the shipping page then we don't get the rates.
2. If the user now adds the same address as new ship to address then we get the rates.
3. If the user has selected default Germany address (or any other country) and when he goes to the shipping page then we get the rates correctly.
4. I don't believe any customizations or code is causing the issue, because we are getting rates for all other conditions and countries. There has to be some config or data issue somewhere for this. Is there any kind of logging for the api call that we can see what might be failing?

Thanks

**Comment by kolevich** [comment]
@HardikGS I did another test for you with the default UK address + another UK address in the address book. Still there are no issues with getting rates: https://www.loom.com/share/9ca6b690face401d9d1bad825be0350d?sid=68f83124-8279-4241-a096-933434e21377

1. Somehow the address entered on the frontend is modified in your Magento and then it doesn't pass the validation. That prevents Magento sending requests to Calcurates. 
2. Calcurates extension is not responsible for post-processing of saved customer addresses, while the cause of the issue is definitely there. 
3. The debug file will show nothing, because Calcurates extension doesn't log invalid addresses.
4. I highly recommend disabling Google address lookup in the "add address" from and test without it.

Thanks.

**Comment by justinaht** [comment]
Hi @kolevich 
I found the problem was due to the validate Dest Region code section
![image](https://github.com/calcurates/module-magento/assets/1575261/90bd0d11-4c55-4c27-91d3-e7bb458333d9)
It is missing region code because Region here is an object of RegionInterface so the region code is missing
![image](https://github.com/calcurates/module-magento/assets/1575261/2cb1d306-fccd-41e8-a579-d1b0e90e8d3b)
I have close this issue
Thanks

**Comment by kolevich** [comment]
@justinaht sounds great! Thanks for letting us know.
